create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null,
  category text not null,
  date date not null,
  read_time text not null default '4 min read',
  city text not null,
  keywords text[] not null default '{}',
  sections jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  city text,
  profile text,
  purpose text,
  arrival_date text,
  contact text not null,
  message text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_news_articles_updated_at on public.news_articles;
create trigger set_news_articles_updated_at
before update on public.news_articles
for each row execute function public.set_updated_at();

alter table public.news_articles enable row level security;
alter table public.consultation_requests enable row level security;
